/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BK
 */
public class SaveGUI extends javax.swing.JFrame {

    /**
     *
     */
    GameGUI gu;

    /**
     *
     */
    String path=null;
   

    /**
     *
     *  
     * @return 
     * @return  
     */
    public GameGUI getGu() {
        return gu;
    }

    /**
     *
     *   gu
     * @param gu
     */
    public void setGu(GameGUI gu) {
        this.gu = gu;
    }

    /**
     * Creates new form SaveGUI
     */
    public SaveGUI() {
        initComponents();
        this.path=SaveGUI.pathCreator();
    }

    /**
     *
     *   gu
     * @param gu
     */
    SaveGUI(GameGUI gu) {
        initComponents();
        this.message.setVisible(false);
        this.setGu(gu);
        this.path=SaveGUI.pathCreator();

        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SettingsB = new javax.swing.JLabel();
        SaveName = new javax.swing.JTextField();
        CloseScreen = new javax.swing.JLabel();
        SaveB = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SettingsB.setAlignmentX(0.5F);
        SettingsB.setAlignmentY(0.0F);
        SettingsB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SettingsB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SettingsBMouseReleased(evt);
            }
        });
        getContentPane().add(SettingsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 356, 35, 35));

        SaveName.setBackground(new java.awt.Color(204, 204, 0));
        SaveName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SaveName.setOpaque(false);
        SaveName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNameActionPerformed(evt);
            }
        });
        getContentPane().add(SaveName, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 165, 332, 25));

        CloseScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseScreenMouseClicked(evt);
            }
        });
        getContentPane().add(CloseScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 80, 30, 20));

        SaveB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SaveBMouseReleased(evt);
            }
        });
        getContentPane().add(SaveB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 298, 190, 30));

        message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package/images/changename350X140.png"))); // NOI18N
        message.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                messageFocusLost(evt);
            }
        });
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 350, 140));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package/images/java src Save clean.png"))); // NOI18N
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackgroundMouseReleased(evt);
            }
        });
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsBMouseReleased
        new SettingsGUI().setVisible(true);
    }//GEN-LAST:event_SettingsBMouseReleased

    private void CloseScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseScreenMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_CloseScreenMouseClicked

    private void SaveNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveNameActionPerformed

    /**
     *
     * @return
     */
    public static String pathCreator() {
        CharSequence win = "Win";
        CharSequence mac = "Mac";
        CharSequence linux = "Lin";
        String tempPath = null;

        String name = System.getProperty("os.name");

        if (name.contains(win)) {
            tempPath = "C:\\BlackJack\\";
            new File(tempPath).mkdir();
        }
        if (name.contains(mac)) {
            tempPath = "BlackJack/";
            new File(tempPath).mkdir();
        }
        if (name.contains(linux)) {
            tempPath = "BlackJack/";
            new File(tempPath).mkdir();
        }
        return tempPath;
    }

    /**
     *
     * @return
     */
    private boolean isAlreadyExist() {
        

        File folder = new File(this.path);
        File[] listOfFiles = folder.listFiles();
        for (int i = 0; (i < listOfFiles.length); i++) {
            listOfFiles[i].setReadOnly();
            if (listOfFiles[i].getName().equalsIgnoreCase(this.SaveName.getText() + ".gm")) {
                return true;
            }
        }
        return false;
    }

    /**
     *
     */
    private void afterSave() {
        
        if (this.isAlreadyExist()) {
            this.message.setVisible(true);
        } else {
            try {
                // TODO add your handling code here:
                this.gu.saveGameToFile(this.path + this.SaveName.getText() + ".gm");

                this.setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(SaveGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void SaveBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBMouseReleased
        afterSave();


    }//GEN-LAST:event_SaveBMouseReleased

    private void BackgroundMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseReleased
        // TODO add your handling code here:
        this.message.setVisible(false);
    }//GEN-LAST:event_BackgroundMouseReleased

    private void messageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageFocusLost
        // TODO add your handling code here:
        this.message.setVisible(false);
    }//GEN-LAST:event_messageFocusLost

    /**
     *   args the command line arguments
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaveGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseScreen;
    private javax.swing.JLabel SaveB;
    private javax.swing.JTextField SaveName;
    private javax.swing.JLabel SettingsB;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
