/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package;

import Classes.Game;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BK
 */
public class SettingsGUI extends javax.swing.JFrame {

    /**
     *
     */
    private GameGUI gu;

    /**
     *
     *  
     * @return 
     * @return  
     */
    public GameGUI getGu() {
        return gu;
    }

    /**
     *
     *   gu
     * @param gu
     */
    public void setGu(GameGUI gu) {
        this.gu = gu;
    }

    /**
     * Creates new form SettingsGUI
     *   aThis
     * @param aThis
     */
    SettingsGUI(GameGUI aThis) {
        initComponents();
        this.setGu(aThis);

    }

    /**
     * Creates new form SettingsGUI
     */
    public SettingsGUI() {
        initComponents();
    }

    /**
     *
     *   gamy
     * @param gamy
     */
    SettingsGUI(Game gamy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SettingsB = new javax.swing.JLabel();
        ReturnB = new javax.swing.JLabel();
        HelpB = new javax.swing.JLabel();
        LoadB = new javax.swing.JLabel();
        ExitB = new javax.swing.JLabel();
        SettingsShortBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SettingsB.setAlignmentX(0.5F);
        SettingsB.setAlignmentY(0.0F);
        SettingsB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SettingsB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SettingsBMouseReleased(evt);
            }
        });
        getContentPane().add(SettingsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 356, 35, 35));

        ReturnB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReturnB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ReturnBMouseReleased(evt);
            }
        });
        getContentPane().add(ReturnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 190, 30));

        HelpB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HelpB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HelpBMouseReleased(evt);
            }
        });
        getContentPane().add(HelpB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 197, 190, 30));

        LoadB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoadB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoadBMouseReleased(evt);
            }
        });
        getContentPane().add(LoadB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 234, 190, 30));

        ExitB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitBMouseReleased(evt);
            }
        });
        getContentPane().add(ExitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 190, 30));

        SettingsShortBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package/images/java src first Short Settings clean.png"))); // NOI18N
        getContentPane().add(SettingsShortBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBMouseReleased
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_ExitBMouseReleased

    private void SettingsBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsBMouseReleased
        this.setVisible(false);
    }//GEN-LAST:event_SettingsBMouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void ReturnBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBMouseReleased
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ReturnBMouseReleased

    private void HelpBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpBMouseReleased
        try {
            new HelpGUI().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(SettingsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HelpBMouseReleased

    private void LoadBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadBMouseReleased
        // TODO add your handling code here:
        new LoadGUI(this).setVisible(true);
        if (this.gu!=null)
            this.gu.setVisible(false);
    }//GEN-LAST:event_LoadBMouseReleased

    /**
     *   args the command line arguments
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitB;
    private javax.swing.JLabel HelpB;
    private javax.swing.JLabel LoadB;
    private javax.swing.JLabel ReturnB;
    private javax.swing.JLabel SettingsB;
    private javax.swing.JLabel SettingsShortBG;
    // End of variables declaration//GEN-END:variables
}
